### ISSUE TITLE
@ prod.secret.exs maybe ?

### ISSUE THREAD

**Issue by JOduMonT** [Pandentia/Dockerfiles#1]
Hi;

would be practical if you give a template for [prod.secret.exs](https://raw.githubusercontent.com/mocknen/docker-pleroma/master/context/prod.secret.exs)
;)

Thank for your image it works very well

**Comment by SapphicCode** [comment]
I'd argue that templating it would defeat the purpose, as pleroma is still very much in development and I'd need to update it as things change. Instead, I'd suggest following the [official configuration instructions](https://git.pleroma.social/pleroma/pleroma#configuration) once, and then using the file generated from there for the Docker container in a bind mount.
